// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aflylwkcjmkrbjusaayf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbHlsd2tjam1rcmJqdXNhYXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTk3MTEsImV4cCI6MjA2NDYzNTcxMX0.rgSowFfblxPZsfYudtI5omqh4FkY1BHCE6oGeuYQxFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);